In [108]:
#q1
import numpy as np
even_arr=np.array([], dtype=int)
for i in range(21,50):
    if i%2==0:
        even_arr=np.append(even_arr,i)
print(even_arr)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [53]:
#q2
import numpy as np
odd_arr=np.array([[1,3,5],[7,9,11],[13,15,17]])
print(odd_arr)
for i in odd_arr:
    for j in i:
        print(j)
    

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
1
3
5
7
9
11
13
15
17


In [10]:
#q3    
import numpy as np
even = np.array([[2,4,6],[8,10,12],[14,16,18]])
even = np.multiply(even,4)
print(even)
print("\n")
id_matrix = np.eye(3, dtype=int)
Matrix=np.multiply(even,id_matrix)
print(Matrix)

[[ 8 16 24]
 [32 40 48]
 [56 64 72]]


[[ 8  0  0]
 [ 0 40  0]
 [ 0  0 72]]


In [105]:
#q4
import numpy as np
data = np.array([('Mujtaba',160,'11th'),('Hilal',170,'11th'),('Attaullah',155,'10th')],
                        dtype={'names':('name','height','class'),
                               'formats':('U10','i4','U10')})
data.sort(order=['class','height'])
print(data)

[('Attaullah', 155, '10th') ('Mujtaba', 160, '11th')
 ('Hilal', 170, '11th')]


In [8]:
#q5
import numpy as np
from numpy import random
odd=[[1,3,5,7],[9,11,13,15],[17,19,21,23],[25,27,29,31]]
arr=random.choice([2,5,9,10], size=(4,4))
print(arr)
print("\n")
id_matrix=np.eye(4, dtype=int)
matrix=np.multiply(arr,id_matrix)
print(matrix)
print("\n")
ans=np.add(matrix,odd)
print(ans)


[[ 5  9  9  9]
 [ 2 10 10  2]
 [ 2  9 10  9]
 [ 5  2 10  5]]


[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0  5]]


[[ 6  3  5  7]
 [ 9 21 13 15]
 [17 19 31 23]
 [25 27 29 36]]


In [6]:
#q6
import numpy as np
a=np.array([[2,3,5],[4,5,7],[7,8,9],[4,6,7],[7,8,9]])
print(a)
b=np.array([[11,10],[9,8],[5,6]])
print("\n")
print(b)
print("\n")
matrix=np.dot(a,b)
print(matrix)

[[2 3 5]
 [4 5 7]
 [7 8 9]
 [4 6 7]
 [7 8 9]]


[[11 10]
 [ 9  8]
 [ 5  6]]


[[ 74  74]
 [124 122]
 [194 188]
 [133 130]
 [194 188]]


In [9]:
#q7
import numpy as np
from numpy import random
x=random.randint(100, size=(1000))
with open("stats.txt","w") as f:
    f.write("Average: {}\n".format(np.average(x)))
    f.write("Variance: {}\n".format(np.var(x)))
    f.write("Standard deviation: {}\n".format(np.std(x)))
f.close()